..\..\vs\x64\Release\YaceReloaded.exe evolve -r 5 ^
top50\armadillo.red ^
top50\arrow.red ^
top50\artofcorewar.red ^
top50\blackknight.red ^
top50\blowrag2.red ^
top50\borgir.red ^
top50\burningmetal.red ^
top50\clairvoyance.red ^
top50\dandelion3.red ^
top50\dawn2.red ^
top50\devilstick.red ^
top50\digeridoo.red ^
top50\dofa.red ^
top50\eccentric.red ^
top50\elvenking.red ^
top50\Eternal_Exile.red ^
top50\excalibur.red ^
top50\forjohn.red ^
top50\frantic.red ^
top50\frothfizzle.red ^
top50\gargantuan.red ^
top50\godsofdestiny.red ^
top50\hairypuffytwins.red ^
top50\halcyon.red ^
top50\hammerhead.red ^
top50\hazylazya70.red ^
top50\hazylazyc11.red ^
top50\herbalavenger.red ^
top50\hescansalone.red ^
top50\hullabaloo.red ^
top50\hullabaloo3.red ^
top50\humanizer.red ^
top50\humanmachine.red ^
top50\idioteque.red ^
top50\infravision.red ^
top50\klr.red ^
top50\kusanagi3.red ^
top50\lastjudgement.red ^
top50\lore2.red ^
top50\luckymisfortune.red ^
top50\maelstrom.red ^
top50\mascafe.red ^
top50\neith.red ^
top50\numb.red ^
top50\olivia.red ^
top50\pdqscan.red ^
top50\pendulum.red ^
top50\perseus.red ^
top50\phatpaper.red ^
top50\pixie.red ^
top50\pppc.red ^
top50\quicksilver.red ^
top50\recon2.red ^
top50\reepicheep.red ^
top50\rust.red ^
top50\shottonothing.red ^
top50\snowscan.red ^
top50\sonofvain.red ^
top50\spiritual.red ^
top50\twobyfour.red ^
top50\waterdragon.red ^
top50\yellownewspaper.red ^
top50\yorba.red